/**
 * Public-facing sample documents surfaced on the /try page so reviewers
 * can experience the full loop without uploading a real Woo document.
 *
 * The PDFs + thumbnails are generated by `tests/fixtures/generate_samples.py`
 * and shipped as static assets under `frontend/static/samples/`.
 *
 * See `docs/todo/done/44-sample-documents-landing.md`.
 */
export interface SampleDoc {
	/** Stable slug used as the PDF + thumbnail basename and the React-style key. */
	id: 'email-thread' | 'raadsverslag' | 'klachtbrief';
	/** File name shown in the UI and registered as the document title. */
	filename: string;
	/** Card title in Dutch. */
	title: string;
	/** One-line Dutch description for the card. */
	description: string;
}

export const SAMPLES: SampleDoc[] = [
	{
		id: 'email-thread',
		filename: 'E-mailwisseling parkeerklacht.pdf',
		title: 'E-mailwisseling tussen ambtenaren',
		description: 'Een thread met doorgestuurde klacht, headers en handtekeningblokken.'
	},
	{
		id: 'raadsverslag',
		filename: 'Verslag commissievergadering.pdf',
		title: 'Verslag van een commissievergadering',
		description: 'Deelnemerslijst met raadsleden, wethouders en insprekers.'
	},
	{
		id: 'klachtbrief',
		filename: 'Klachtbrief huurtoeslag.pdf',
		title: 'Klachtbrief van een burger',
		description: 'Brief met BSN, IBAN, adres en andere harde identificatoren.'
	}
];
